automation: add glusterfs 3.10 repository
Resolves:
 Error: Package: vdsm-4.20.2-47.gitef4630a.el7.centos.x86_64 (ovirt-master-snapshot)
        Requires: glusterfs-fuse >= 3.10
        Available: glusterfs-fuse-3.7.9-12.el7.centos.x86_64 (centos-base-el7)

Change-Id: I59931ab40f5db07ca1b0ff7d9a8d76d73a133e6d
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>